### Exercise 1: Implementing a Mathematical Equation

In [1]:
import tensorflow as tf
X=tf.Variable(3)
Y=tf.Variable(4)
C=tf.constant(2)
def myfunc(x,y,c):
  Z=x*x*y+y+c
  return Z

result=myfunc(X,Y,C)
tf.print(result)




42


### Exercise 2: Matrix Multiplication Using TensorFlow

In [2]:
import tensorflow as tf
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [3]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [4]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [5]:
c1=tf.matmul(X,Y)

In [6]:
tf.print(c1)

[[58 64]
 [139 154]]


In [8]:
c2=tf.matmul(Y,X)

In [9]:
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]


### Exercise 3: Reshaping Matrices Using the reshape() Function in TensorFlow

In [10]:
import tensorflow as tf
A=tf.Variable([[1,2,3,4], \
[5,6,7,8], \
[9,10,11,12], \
[13,14,15,16], \
[17,18,19,20]])

In [11]:
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [12]:
A.shape

TensorShape([5, 4])

In [13]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [14]:
A.shape

TensorShape([5, 4])

In [15]:
A = tf.reshape(A,[5,4,1])

In [17]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


### Exercise 4: Implementing the argmax() Function

In [18]:
import tensorflow as tf
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])

In [19]:
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [20]:
X.shape

TensorShape([3, 3])

In [21]:
tf.print(tf.argmax(X,axis=0))

[0 1 2]


In [22]:
tf.print(tf.argmax(X,axis=1))

[0 1 0]


### Exercise 5: Using an Optimizer for a Simple Linear Regression

In [23]:
import tensorflow as tf
w=tf.Variable(0.0)
b=tf.Variable(0.0)

In [24]:
def regression(x):
  model=w*x+b
  return model

In [25]:
x=[1,2,3,4]
y=[0,-1,-2,-3]

In [26]:
loss=lambda:abs(regression(x)-y)

In [28]:
optimizer=tf.optimizers.Adam(.01)
for i in range(1000):
  optimizer.minimize(loss,[w,b])


In [29]:
tf.print(w,b)

-1.00371706 0.999803364


In [30]:
tf.print(regression([1,2,3,4]))

[-0.00391370058 -1.00763083 -2.01134801 -3.01506495]


### Exercise 6: Creating an ANN with TensorFlow

In [31]:
import tensorflow as tf

In [32]:
model = tf.keras.Sequential()

In [34]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,)
, \
name='Input_layer'))

In [36]:
model.add(tf.keras.layers.Dense(4, activation='relu',
\
name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1,
name='Output_layer'))

In [37]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[-0.07637513, -0.32552877,  0.693227  , -0.16198939],
        [ 0.09430122,  0.03911191, -0.3438244 ,  0.6318268 ],
        [ 0.689547  ,  0.4169193 ,  0.38456994,  0.21591508],
        [-0.5971397 , -0.67901033,  0.07358062, -0.04448164],
        [ 0.6920696 ,  0.48127347,  0.6183291 ,  0.48996288],
        [-0.44465026, -0.61380243, -0.14866275,  0.6106245 ],
        [-0.33075833,  0.37761468,  0.16238034, -0.28132817],
        [ 0.14332843,  0.4312175 , -0.5016935 , -0.4738518 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.7380357 ],
        [-0.54979736],
        [ 0.4240303 ],
        [-1.0035791 ]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [38]:
data = tf.random.normal((32,8))

In [40]:
prediction=model.predict(data)


1/1 [==============================] - 0s 30ms/step


In [41]:
prediction

array([[-1.0724299 ],
       [ 0.08208106],
       [ 1.356426  ],
       [ 0.        ],
       [ 0.4525504 ],
       [ 1.6630293 ],
       [-0.31866747],
       [-0.31113634],
       [-1.8645376 ],
       [ 0.03782332],
       [ 0.        ],
       [ 0.24272446],
       [ 0.79493207],
       [ 0.        ],
       [-0.98393863],
       [ 0.        ],
       [ 0.72978455],
       [-0.1493119 ],
       [ 0.09569356],
       [ 0.04064929],
       [ 0.00870094],
       [-0.4414781 ],
       [ 0.6122229 ],
       [-0.17157134],
       [-0.02978003],
       [ 1.1728387 ],
       [ 0.51809484],
       [-0.52595973],
       [ 0.8348085 ],
       [-0.3349426 ],
       [-0.43992966],
       [-0.9920026 ]], dtype=float32)

### Exercise 7: Creating a Linear Regression Model as an ANN with TensorFlow

In [42]:
import tensorflow as tf
import pandas as pd

In [43]:
df = pd.read_csv('Bias_correction_ucl.csv')

In [44]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [45]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)

In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [47]:
model = tf.keras.Sequential()

In [48]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

In [49]:
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [50]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [52]:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [53]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50,
callbacks=[tensorboard_callback])

Epoch 1/50
238/238 [==============================] - 1s 1ms/step - loss: 634.0229
Epoch 2/50
238/238 [==============================] - 1s 2ms/step - loss: 532.1064
Epoch 3/50
238/238 [==============================] - 1s 3ms/step - loss: 440.0432
Epoch 4/50
238/238 [==============================] - 0s 2ms/step - loss: 357.5184
Epoch 5/50
238/238 [==============================] - 0s 1ms/step - loss: 284.5779
Epoch 6/50
238/238 [==============================] - 0s 2ms/step - loss: 221.1716
Epoch 7/50
238/238 [==============================] - 0s 2ms/step - loss: 167.2987
Epoch 8/50
238/238 [==============================] - 0s 1ms/step - loss: 123.1529
Epoch 9/50
238/238 [==============================] - 0s 1ms/step - loss: 88.4325
Epoch 10/50
238/238 [==============================] - 0s 1ms/step - loss: 63.0249
Epoch 11/50
238/238 [==============================] - 0s 1ms/step - loss: 45.4565
Epoch 12/50
238/238 [==============================] - 0s 1ms/step - loss: 33.4013
Epoch

In [54]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 1ms/step - loss: 3.5391
loss: 3.539133071899414


### Exercise 8: Creating a Multi-Layer ANN with TensorFlow

In [55]:
import tensorflow as tf
import pandas as pd

In [56]:
df = pd.read_csv('Bias_correction_ucl.csv')

In [57]:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [58]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)

In [59]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [60]:
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [61]:
model = tf.keras.Sequential()

In [62]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape
[1],), \
name='Input_layer'))

In [63]:
model.add(tf.keras.layers.Dense(16,
name='Dense_layer_1'))
model.add(tf.keras.layers.Dense(8,
name='Dense_layer_2'))
model.add(tf.keras.layers.Dense(4,
name='Dense_layer_3'))
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [64]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [66]:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [67]:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50, callbacks=[tensorboard_callback]
, \
validation_split=0.2)

Epoch 1/50
190/190 [==============================] - 2s 4ms/step - loss: 325.4510 - val_loss: 19.0510
Epoch 2/50
190/190 [==============================] - 1s 6ms/step - loss: 10.4076 - val_loss: 5.9408
Epoch 3/50
190/190 [==============================] - 1s 5ms/step - loss: 4.5007 - val_loss: 4.5931
Epoch 4/50
190/190 [==============================] - 0s 2ms/step - loss: 3.3955 - val_loss: 3.9320
Epoch 5/50
190/190 [==============================] - 0s 2ms/step - loss: 2.8610 - val_loss: 3.5845
Epoch 6/50
190/190 [==============================] - 0s 2ms/step - loss: 2.5347 - val_loss: 3.1262
Epoch 7/50
190/190 [==============================] - 1s 3ms/step - loss: 2.3213 - val_loss: 3.0062
Epoch 8/50
190/190 [==============================] - 0s 2ms/step - loss: 2.1649 - val_loss: 2.7236
Epoch 9/50
190/190 [==============================] - 0s 2ms/step - loss: 2.0589 - val_loss: 2.5827
Epoch 10/50
190/190 [==============================] - 0s 2ms/step - loss: 1.9675 - val_loss: 2.

In [68]:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 2ms/step - loss: 1.8641
loss: 1.864100456237793


### Exercise 9: Creating a Logistic Regression Model as an ANN with TensorFlow

In [69]:
import tensorflow as tf
import pandas as pd

In [74]:
df = pd.read_csv('qsar_androgen_receptor.csv', sep=';')

In [75]:
df.dropna(inplace=True)

In [76]:
target = df['positive'].apply(lambda x: 1 if
x=='positive' else 0)
features = df.drop('positive', axis=1)

In [77]:
model = tf.keras.Sequential()

In [78]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

In [79]:
model.add(tf.keras.layers.Dense(1,
name='Output_layer', \
activation='sigmoid')
)

In [80]:
model.compile(tf.optimizers.RMSprop(0.0001), \
loss='binary_crossentropy',
metrics=['accuracy'])

In [83]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="./logs")

In [84]:
model.fit(x=features.to_numpy(), y=target.to_numpy(),
epochs=50, callbacks=[tensorboard_callback], validation_split=0.2)

Epoch 1/50
43/43 [==============================] - 1s 6ms/step - loss: 0.6290 - accuracy: 0.7107 - val_loss: 0.5283 - val_accuracy: 0.8728
Epoch 2/50
43/43 [==============================] - 0s 3ms/step - loss: 0.5787 - accuracy: 0.8049 - val_loss: 0.4615 - val_accuracy: 0.9201
Epoch 3/50
43/43 [==============================] - 0s 3ms/step - loss: 0.5438 - accuracy: 0.8383 - val_loss: 0.4154 - val_accuracy: 0.9231
Epoch 4/50
43/43 [==============================] - 0s 3ms/step - loss: 0.5182 - accuracy: 0.8591 - val_loss: 0.3848 - val_accuracy: 0.9231
Epoch 5/50
43/43 [==============================] - 0s 3ms/step - loss: 0.4993 - accuracy: 0.8665 - val_loss: 0.3641 - val_accuracy: 0.9260
Epoch 6/50
43/43 [==============================] - 0s 3ms/step - loss: 0.4844 - accuracy: 0.8694 - val_loss: 0.3469 - val_accuracy: 0.9260
Epoch 7/50
43/43 [==============================] - 0s 3ms/step - loss: 0.4714 - accuracy: 0.8702 - val_loss: 0.3363 - val_accuracy: 0.9260
Epoch 8/50
43/43 [==

In [85]:
loss, accuracy = model.evaluate(features.to_numpy(),
\
target.to_numpy())
print(f'loss: {loss}, accuracy: {accuracy}')

53/53 [==============================] - 0s 2ms/step - loss: 0.2782 - accuracy: 0.9116
loss: 0.278238445520401, accuracy: 0.9116251468658447
